"""Typed contracts for the site-selection analysis workflow."""

from .agents import (
    AgentRole,
    OrchestratorAgent,
    OrchestratorAgentInput,
    OrchestratorAgentOutput,
    PolicyAgent,
    PolicyAgentInput,
    PolicyAgentOutput,
    ReviewAgent,
    ReviewAgentInput,
    ReviewAgentOutput,
    SpatialAgent,
    SpatialAgentBlockedError,
    SpatialAgentInput,
    SpatialAgentOutput,
)
from .comparison import (
    CandidateComparisonBlockedError,
    compare_candidate_results,
)
from .constraints import (
    ConstraintLayerSpec,
    ConstraintLayerType,
    ConstraintObservation,
    SpatialConstraintRelation,
)
from .domain import (
    CandidateParcel,
    DatasetManifest,
    DatasetSource,
    ProjectRequest,
    ProjectType,
)
from .evidence import (
    AgentState,
    AnalysisResult,
    AnalysisStatus,
    CandidateComparisonItem,
    CandidateComparisonReport,
    EvidenceStatus,
    GISEvidence,
    POIEvidence,
    PolicyEvidence,
)
from .intake import (
    ProfileRegistry,
    ProjectIntakeSkill,
    ProjectTypeRouter,
    UnsupportedProjectTypeError,
    build_poi_queries,
)
from .poi import (
    POIFeatureSet,
    POIMetric,
    POIProvider,
    POIQuery,
    POIRecord,
    POISourceMeta,
)
from .poi_service import (
    MockPOIGateway,
    POIGateway,
    calculate_poi_metrics,
    execute_poi_queries,
)
from .poi_scoring import (
    MissingMetricPolicy,
    POIGroupScore,
    POIGroupScoringConfig,
    POIMetricScore,
    POIMetricScoringRule,
    POIScoreReport,
    POIScoringConfig,
    POIScoringError,
    ScoreDirection,
    normalize_metric_value,
    score_poi_feature_sets,
)
from .poi_scoring_service import score_poi_state
from .poi_adapters import (
    FixturePOIAdapter,
    FixturePOIDataset,
    POISourceAdapter,
    haversine_distance_m,
)
from .preflight import (
    PreflightDecision,
    PreflightStatus,
    SiteSelectionDraft,
    evaluate_site_selection_draft,
)
from .profiles import (
    PROJECT_PROFILES,
    POICategoryConfig,
    ProjectProfile,
    get_project_profile,
)
from .results import ResultAssemblyBlockedError, assemble_analysis_results
from .rule_engine import (
    RuleConfigurationError,
    RuleEvaluationBlockedError,
    evaluate_policy_rules,
)
from .rules import (
    PolicyFinding,
    PolicyReference,
    RuleDefinition,
    RuleOutcome,
)
from .workflow import (
    SiteSelectionWorkflowDependencies,
    WorkflowEvidenceBlockedError,
    build_site_selection_graph,
    route_after_step,
    run_site_selection_workflow,
)

__all__ = [
    "AgentState",
    "AgentRole",
    "AnalysisResult",
    "AnalysisStatus",
    "CandidateComparisonBlockedError",
    "CandidateComparisonItem",
    "CandidateComparisonReport",
    "CandidateParcel",
    "ConstraintLayerSpec",
    "ConstraintLayerType",
    "ConstraintObservation",
    "DatasetManifest",
    "DatasetSource",
    "EvidenceStatus",
    "FixturePOIAdapter",
    "FixturePOIDataset",
    "GISEvidence",
    "MockPOIGateway",
    "MissingMetricPolicy",
    "POICategoryConfig",
    "POIGroupScore",
    "POIGroupScoringConfig",
    "POIEvidence",
    "POIFeatureSet",
    "POIGateway",
    "POIMetric",
    "POIMetricScore",
    "POIMetricScoringRule",
    "POIProvider",
    "POIQuery",
    "POIRecord",
    "POISourceMeta",
    "POIScoreReport",
    "POIScoringConfig",
    "POIScoringError",
    "POISourceAdapter",
    "PROJECT_PROFILES",
    "PolicyEvidence",
    "PolicyFinding",
    "PolicyReference",
    "PolicyAgent",
    "PolicyAgentInput",
    "PolicyAgentOutput",
    "PreflightDecision",
    "PreflightStatus",
    "ProfileRegistry",
    "ProjectIntakeSkill",
    "ProjectProfile",
    "ProjectRequest",
    "ProjectType",
    "ProjectTypeRouter",
    "OrchestratorAgent",
    "OrchestratorAgentInput",
    "OrchestratorAgentOutput",
    "ResultAssemblyBlockedError",
    "RuleConfigurationError",
    "RuleDefinition",
    "RuleEvaluationBlockedError",
    "RuleOutcome",
    "ReviewAgent",
    "ReviewAgentInput",
    "ReviewAgentOutput",
    "ScoreDirection",
    "SiteSelectionWorkflowDependencies",
    "SpatialConstraintRelation",
    "SpatialAgent",
    "SpatialAgentBlockedError",
    "SpatialAgentInput",
    "SpatialAgentOutput",
    "SiteSelectionDraft",
    "UnsupportedProjectTypeError",
    "WorkflowEvidenceBlockedError",
    "assemble_analysis_results",
    "build_poi_queries",
    "build_site_selection_graph",
    "calculate_poi_metrics",
    "compare_candidate_results",
    "evaluate_policy_rules",
    "execute_poi_queries",
    "evaluate_site_selection_draft",
    "get_project_profile",
    "haversine_distance_m",
    "normalize_metric_value",
    "route_after_step",
    "run_site_selection_workflow",
    "score_poi_feature_sets",
    "score_poi_state",
]
